# Generated by Django 6.0.7 on 2026-08-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_emailverificationtoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='profile_type',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=10),
        ),
    ]
