# Generated by Django 6.0.7 on 2026-08-04 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merchantprofile_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantprofile',
            name='merchant_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='merchantprofile',
            name='merchant_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='merchantprofile',
            name='merchant_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='merchantprofile',
            name='merchant_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='merchantprofile',
            name='merchant_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='merchantprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
