# Generated by Django 6.0.7 on 2026-08-04 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_merchantprofile_merchant_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
