# Generated by Django 6.0.7 on 2026-08-04 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_merchantprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchantprofile',
            old_name='profile_type',
            new_name='user_type',
        ),
    ]
