# Generated by Django 6.0.7 on 2026-08-04 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_profile_type_merchantprofile_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantprofile',
            name='merchant_category',
        ),
        migrations.RemoveField(
            model_name='merchantprofile',
            name='merchant_website',
        ),
    ]
