# Generated by Django 6.0.7 on 2026-08-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Naira'), ('USD', 'Dollar'), ('EUR', 'Euro')], default='NGN', max_length=3),
        ),
        migrations.AddField(
            model_name='wallet',
            name='request_origin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('LOCKED', 'Locked'), ('FROZEN', 'Frozen')], default='ACTIVE', max_length=10),
        ),
    ]
